Update to use a NSOperationQueue instead of GCD
spotify/SPTPersistentCache pull request #78
Opened 2016-10-14 19:19 UTC by chrisbtreats

After analyzing some performance numbers, it seemed that a large number of interactions on the persistent cache where causing long read times. It turns out that you can flood the execution queue with things like unlocking or deleting and they would block operations like reads until the queue finished all of the operations that were enqueued before the read. The idea with this PR is to use a priority queue in the form of NSOperationQueue to allow reads to have a higher priority for reads than for unlocks or deletes.

I added some timing and a performance test in `SPTPersistentCachePerformance` that creates 200 locked items in the cache and then enqueues 200 unlocks followed immediately by 200 reads. I ran the test 3 times, first on the current GCD version and then on 2 versions using the NSOperationQueue, first with normal priority for all operation types and then with a high priority for reads and a low priority for unlocks.

Here are the times of the read sitting in the queue before execution begins. The test was run on an iPhone 6 running iOS 9.3.5. All times are in milliseconds.

Type|Queue Average|Queue Min|Queue Max
---|---|---|---
Current GCD | 372.1658762 |51.09783|968.4579
NSOperationQueue Normal|348.2155414|33.32054|963.0783
NSOperationQueue Priority|328.9230705|12.22912|909.4095

This shows close to a 12% increase in the average queue time and a 6% improvement over the max wait time.

There are some backwards compatibility breaking changes in this that modify a few methods (such as `removeDataForKeys`, `prune`,  `wipeLockedFiles`, and `wipeNonLockedFiles`) to be asynchronous instead of synchronous.

2016-10-14 21:25 UTC, rastersize requested changes
Thank you for your PR @chrisbtreats, this looks very interesting!

How long will these performance tests normally take to run? I saw a few timeouts and sleeps for
relatively long durations and I’m curious whether we should run it by default or not.

2016-10-14 21:25 UTC, rastersize commented on SPTPersistentCache.xcodeproj/project.pbxproj
> +		772B8BF11D6DE879008E7347 /* SPTPersistentCachePerformance.m in Sources */ = {isa = PBXBuildFile; fileRef = 772B8BF01D6DE879008E7347 /* SPTPersistentCachePerformance.m */; };
Please rename this file to `SPTPersistentCachePerformanceTests.m`.

2016-10-14 21:25 UTC, rastersize commented on Tests/SPTPersistentCachePerformance.m
> +@interface SPTPersistentCachePerformance : XCTestCase
Suffix class name with `Tests`

2016-10-14 21:25 UTC, rastersize commented on Tests/SPTPersistentCachePerformance.m
> +
Remove this empty line

2016-10-14 21:25 UTC, rastersize commented on include/SPTPersistentCache/SPTPersistentCacheOptions.h
> +    SPTPersistentCacheDebugMethodTypeStore = 0,
Since the raw value of the enum value isn’t used or relied up we could remove those. Should make maintenance easier.

2016-10-14 21:25 UTC, rastersize commented on include/SPTPersistentCache/SPTPersistentCacheOptions.h
> +    SPTPersistentCacheDebugTimingTypeQueued = 0,
Since the raw value of the enum value isn’t used or relied up we could remove those. Should make maintenance easier.

2016-10-14 21:25 UTC, rastersize commented on include/SPTPersistentCache/SPTPersistentCacheOptions.h
> +typedef NS_ENUM(NSUInteger, SPTPersistentCacheDebugTimingType) {
A documentation string would be lovely 😺

2016-10-14 21:25 UTC, rastersize commented on include/SPTPersistentCache/SPTPersistentCacheOptions.h
> +typedef NS_ENUM(NSUInteger, SPTPersistentCacheDebugMethodType) {
A documentation string would be lovely 😺

2016-10-14 21:25 UTC, rastersize commented on include/SPTPersistentCache/SPTPersistentCacheOptions.h
> +typedef void (^SPTPersistentCacheDebugTimingCallback)(NSString *key, SPTPersistentCacheDebugMethodType method, SPTPersistentCacheDebugTimingType type, uint64_t machTime);
Could we document this type as well?

2016-10-14 21:25 UTC, rastersize commented on include/SPTPersistentCache/SPTPersistentCacheOptions.h
> +@property (nonatomic, copy, nullable) SPTPersistentCacheDebugTimingCallback timingCallback;
Could we document this property 😺

2016-10-14 21:25 UTC, rastersize commented on include/SPTPersistentCache/SPTPersistentCache.h
> +- (void)pruneWithCallback:(SPTPersistentCacheResponseCallback _Nullable)callback
How about keeping `- (void)prune` as a convenience method, which would also decrease the amount of API breakage.

2016-10-14 21:25 UTC, rastersize commented on include/SPTPersistentCache/SPTPersistentCache.h
> +- (void)removeDataForKeys:(NSArray<NSString *> *)keys
Could we make this an additive change instead, keeping the old method around so we don’t break the current API?

2016-10-14 21:25 UTC, rastersize commented on include/SPTPersistentCache/SPTPersistentCache.h
> +- (void)wipeLockedFilesWithCallback:(SPTPersistentCacheResponseCallback _Nullable)callback
Could we make this an additive change instead, keeping the old method around so we don’t break the current API?

2016-10-14 21:25 UTC, rastersize commented on include/SPTPersistentCache/SPTPersistentCache.h
> +- (void)wipeNonLockedFilesWithCallback:(SPTPersistentCacheResponseCallback _Nullable)callback
Same here, could we make this an additive change instead, keeping the old method around so we don’t break the current API?

2016-10-14 21:25 UTC, rastersize commented
Also looping in @spotify/objc-dev since the changes are quite significant for a second pair of 👀

2016-10-14 23:47 UTC, chrisbtreats commented
I think the performance tests took less than a minutes to run. I don't think they need to run each time and can be disabled by default. They are here mostly for conversation. I will update the missing documentation on Monday. The main reason I didn't leave the synchronous version of those methods is that NSOperationQueue doesn't really have an equivalent to `dispatch_barrier_async` and it would require much more work to emulate that.

2016-10-15 00:51 UTC, chrisbtreats commented
Looks like build error `[invalid license header]` which I will fix on Monday as well. I will also merge in master to fix the conflicts.

2016-10-15 00:56 UTC, rastersize commented
@chrisbtreats Let's keep the test disabled in the Xcode scheme then. So we don't add another minute to our internal test suit 😬

Ping me when you've updated the PR and I'll have a look again.

2016-10-16 08:57 UTC, 8W9aG commented on Tests/SPTPersistentCachePerformance.m
> +    while (kFileNames[i] != NULL) {
Instead of putting NULL in the array you can use the sizeof() call since it is statically allocated

2016-10-16 08:57 UTC, 8W9aG commented on Tests/SPTPersistentCachePerformance.m
> +    if(![[NSFileManager defaultManager] removeItemAtPath:self.cachePath error:&error]){
if () {

2016-10-17 19:43 UTC, chrisbtreats commented
@rastersize I slightly misunderstood what `dispatch_barrier_async` was doing and it wasn't actually synchronous before. It is asynchronous but ensures exclusive execution of the task while no other tasks are executing. `NSOperationQueue` doesn't have an equivalent to `dispatch_barrier_async`. I can add those existing methods back but it worries me to have the same method having different semantics of guaranteeing one operation at a time. My thought was it was better to have a breaking change than to have different semantics. One option is to leave the old methods with different semantics and mark them as deprecated.

2016-10-18 13:59 UTC, chrisbtreats commented
Builds seem to be broken on things I didn't touch. Maybe the recent build updates broke this? After merging in master, even the tests fail to compile locally. Complaining about unknown doc tag `@private` in XCTestCase.h.

2016-10-19 18:40 UTC, chrisbtreats commented
What do we want to do about this error? Should be use a minimum OS X version of 10.10 or put a conditional around the code? 

> /Users/travis/build/spotify/SPTPersistentCache/Sources/SPTPersistentCacheGarbageCollector.m:80:15: 'qualityOfService' is partial: introduced in OS X 10.10

2016-10-19 19:02 UTC, rastersize commented
@chrisbtreats I think it’s because newer Xcode versions have enabled stricter warnings for documentation strings. I’d suggest we add the `_Pragma()` push/ignore/pop dance around the import of XCTest. As well as a comment on why.

2016-10-19 22:19 UTC, 8W9aG commented
Also if you only want to support OSX 10.10 then that's fine with me

2016-10-20 15:49 UTC, chrisbtreats commented
Git is not happy. Closing and reopening a new one.

2016-10-20 15:49 UTC, closed without merging

2016-10-20 16:07 UTC, chrisbtreats commented
Moved to https://github.com/spotify/SPTPersistentCache/pull/81